---
- name: Deploy webapp
  hosts: web
  become: true

  tasks:

  - name: Install Apache
    ansible.builtin.yum:
      name: "{{ web_service }}"
      state: latest

  - name: Install PHP and mod_ssl
    ansible.builtin.yum:
      name: "{{ item }}"
      state: latest
    loop:
      - php
      - php-mysqlnd
      - mod_ssl

  - name: Set the correct selinux booleans
    ansible.posix.seboolean:
      name: "{{ item }}"
      state: true
      persistent: true
    loop:
      - httpd_can_network_connect
      - httpd_can_network_connect_db

  - name: Enable and start the apache server
    ansible.builtin.service:
      name: "{{ web_service }}"
      state: started
      enabled: true

  - name: Allow port 80 and 443 through the firewall
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    with_items:
      - "{{ firewall_services }}"

  - name: Drop in index.php file
    ansible.builtin.template:
      src: templates/index.php.j2
      dest: /var/www/html/index.php
